apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-index
  namespace: aeteq-dev
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: split-index
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: split-index
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: split-index
          image: ghcr.io/kgomotso1995/split_index:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
